language: python
python:
  - 3.4

env:
  - MODULE=server
  - MODULE=client

matrix:
  fast_finish: true

before_install:
  - case ${MODULE} in
      server) pip install coveralls;;
      client) export NPM_CONFIG_SPIN=false;
              npm install -g codeclimate-test-reporter;
              export CHROME_BIN=chromium-browser;
              export DISPLAY=:99.0;
              sh -e /etc/init.d/xvfb start;;
    esac
  - export GLOBAL_INSTALL=true

install:
  - server/package.sh install --force
  - case ${MODULE} in
      client) client/package.sh install --force;;
    esac

before_script:
  - server/package.sh manage_database --create
  - config/package.sh make_defaults
  - case ${MODULE} in
      client) server/package.sh start & sleep 3;;
    esac

script:
  - case ${MODULE} in
      server) server/package.sh test -vv --full-trace;;
      client) client/package.sh test;;
    esac

after_success:
  - case ${MODULE} in
      server) (cd server; coveralls --rcfile .coveragerc);;
      client) (cd client; find tmp/coverage -name lcov.info -exec cat {} \; | codeclimate);;
    esac
