language: python
python:
  - 3.4

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - pip install coveralls
  - export GLOBAL_INSTALL=true

install:
  - server/package.sh install
  - client/package.sh install

  - client/package.sh update_webdriver

  - server/package.sh manage_database --create

script:
  - server/package.sh test -vv --full-trace

  - server/package.sh start & sleep 3
  - client/package.sh test

after_success:
  - (cd server; coveralls --rcfile .coveragerc)
