language: python
python:
  - 3.4
install:
  - pip install -r server/requirements.txt
  - pip install coveralls
script:
  - py.test --cov server/app --cov-config server/.coveragerc --cov-report=term-missing server/test
after_success:
  - coveralls --rcfile server/.coveragerc
