sudo: false
language: python
python:
  - 3.4

env:
  global:
    - NPM_CONFIG_SPIN=false
    - NPM_CONFIG_PYTHON=python2
    - DISPLAY=:99.0
  matrix:
    - MODULE=server
    - MODULE=client

matrix:
  fast_finish: true

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

cache:
  - pip
  - npm
  - directories:
    - $HOME/.cache/pip
    - $HOME/.npm

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - pip install --upgrade pip setuptools wheel
  - case ${MODULE} in
      server) pip install --upgrade coveralls;;
      client) . $HOME/.nvm/nvm.sh;
              nvm install 4.3;
              nvm use 4.3;
              npm install -g npm codeclimate-test-reporter;
              sh -e /etc/init.d/xvfb start;;
    esac

install:
  - export GLOBAL_INSTALL=true
  - server/package.sh install --force
  - case ${MODULE} in
      client) client/package.sh install --force;;
    esac

before_script:
  - ./package.sh make_defaults
  - ./package.sh upgrade_database
  - case ${MODULE} in
      client) ./package.sh start & sleep 3;;
    esac

script:
  - case ${MODULE} in
      server) server/package.sh test -f -vv --full-trace;;
      client) client/package.sh test;;
    esac

after_success:
  - case ${MODULE} in
      server) (cd server; coveralls --rcfile .coveragerc);;
      client) (cd client; find tmp/coverage -name lcov.info -exec cat {} \; | codeclimate-test-reporter);;
    esac
