language: python
python:
  - 3.4
install:
  - pip install -r server/requirements.txt
  - pip install coveralls
script:
  - coverage run --rcfile server/.coveragerc server/test.py
  - coverage report --rcfile server/.coveragerc -m
after_success:
  - coveralls --rcfile server/.coveragerc
