USED_CONFIG: DefaultConfig


DefaultConfig:
  App:
    NAME: "storekeeper"
    TITLE: "StoreKeeper"

    ADMIN_PAGE: False
    MIGRATE_REPO_PATH: "$BASEDIR/db_repository"
    SHARE_STATIC: True

  Flask:
    # http://flask.pocoo.org/docs/0.10/config/
    SECRET_KEY: ImportantSecretString
    DEBUG: False
    TESTING: False

    # https://pythonhosted.org/Flask-SQLAlchemy/config.html
    SQLALCHEMY_DATABASE_URI: "sqlite:///$BASEDIR/app.sqlite"

    ALLOW_API_SIMPLE_AUTH: False


ProductionConfig:
  Base: DefaultConfig

  App:
    SHARE_STATIC: False

  Flask:
    SQLALCHEMY_DATABASE_URI: "mysql+pymysql://storekeeper:StoreKeeper@localhost/storekeeper"


DevelopmentConfig:
  Base: DefaultConfig

  App:
    ADMIN_PAGE: True

  Flask:
    WTF_CSRF_ENABLED: False
    DEBUG: True

    # http://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xvi-debugging-testing-and-profiling
    # SQLALCHEMY_RECORD_QUERIES = True


TestingConfig:
  Base: DefaultConfig

  App:
    MIGRATE_REPO_PATH: "$BASEDIR/tmp/test_db_repository"

  Flask:
    WTF_CSRF_ENABLED: False
    TESTING: True

    # Most of SQL related tests override this settings and use in-memory database, however tests of DatabaseMaintenance
    # class have to use file based database!
    SQLALCHEMY_DATABASE_URI: "sqlite:///$BASEDIR/tmp/test.sqlite"
